# Generated by Django 3.0.5 on 2020-05-07 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_child', models.CharField(default='name', max_length=50, verbose_name='Name child')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_family', models.CharField(default='name', max_length=50, verbose_name='Name family')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=20, verbose_name='Name child')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=50, verbose_name='Name task')),
                ('info_task', models.CharField(max_length=200, null=True, verbose_name='Info task')),
                ('point_task', models.IntegerField(verbose_name='Point')),
                ('id_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.Child', verbose_name='Child')),
                ('id_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.Family', verbose_name='Family')),
                ('id_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.Status', verbose_name='Status')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
