# Generated by Django 3.0.5 on 2020-05-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0001_initial'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Family.Family', verbose_name='Family'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
